### PR TITLE
Use apply to format fields for database insertion to avoid write.table

### PR DESCRIPTION
**Pull request by awchisholm**
Write table creates a global variable.

### CODE REVIEW

**Comment by hannesmuehleisen** [comment]
I wonder why the quoting is removed, since that will break inserting text that contains \t or am I missing something?

**Comment by awchisholm** [comment]
That's a good point; the data I have is well behaved so I didn't stumble across that. I will try to find a way to add quotes that doesn't too complicated.

**Comment by awchisholm** [comment]
I have made a simple edit to cater for embedded tab characters. I noticed that numbers are rendered differently now. The new code causes an additional `.0` to be added to integer values if there is a single example in a column that is numeric but not an exact integer.

**Comment by awchisholm** [comment]
Hello Hannes

Sorry for delayed reply - back from holiday now

I think I have found an alternative that uses write.table - there is a
local flag to the function textConnection that looks like it will cause the
value_str variable to be local. At the moment, value_str appears in the
namespace of the caller and cannot be modified later which leads to a
crash. I'll try it later today to confirm.

regards

Andrew

**Pull request merged**
